# -*- coding: utf-8 -*-
"""Python Session05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162GbhJz9XJ7ZCMjJmA7BueeSR1glBwKH
"""

import pandas as pd
df = pd.read_excel("/Customers.xlsx", header=3)

df.head()

df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df.head()

df.info()

df['JoinDate'] = pd.to_datetime(df['JoinDate'], dayfirst=True, errors='coerce')
df.info()
df.head()

df_cleaned = df.dropna()
df_cleaned.info()
df_cleaned.head()

distinct_regions = df_cleaned['Region'].unique()
print("Distinct values in the 'Region' column:")
for region in distinct_regions:
    print(region)

distinct_SalesRep = df_cleaned['SalesRep'].unique()
print("Distinct values in the 'SalesRep' column:")
for SalesRep in distinct_SalesRep:
    print(SalesRep)

distinct_Customer = df_cleaned['CustomerName'].unique()
print("Distinct values in the 'CustomerName' column:")
for CustomerName in distinct_Customer:
    print(CustomerName)

print(f"Number of unique Regions: {len(distinct_regions)}")
print(f"Number of unique SalesReps: {len(distinct_SalesRep)}")
print(f"Number of unique Customer Names: {len(distinct_Customer)}")

region_counts = df_cleaned['Region'].value_counts()
print("Repetitions for 'Region' column:")
display(region_counts)

SalesRep_counts = df_cleaned['SalesRep'].value_counts()
print("Repetitions for 'SalesRep' column:")
display(SalesRep_counts)