# -*- coding: utf-8 -*-
"""Python Session 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157QbUEFa3oN4uTbNJjZRSxX0L_2Ig9mX
"""

import numpy as np
grid = [1,2,3,4,5]
a= np.array(grid)
print(a)

b = np.zeros(grid)
print(b)

c = np.ones(grid)
print(c)

d = np.arange(start=0,stop=10,step=2)
print(d)

e = np.eye(3)
print(e)

f = np.add(e,e)
print(f)

g = np.subtract(e,f)
print(g)

h = np.multiply(e,f)
print(h)

i = np.power(h,h)
print(i)

j = np.mean(grid)
k = np.median(grid)
l = np.std(grid)
m = np.var(grid)
n = np.min(grid)
o = np.max(grid)
p = np.sum(grid)
print(j,k,l,m,n,o,p,)
