# -*- coding: utf-8 -*-
"""Python Session 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10N5vWZ8EApXabckFUYi5BLCbmBhmOMo0

Reverse a String
"""

X = "Python is important for Data Science"
Rev = ""
for char in X:
    Rev = char + Rev
print(Rev)

"""Check if String is Palindrome"""

Y = "madam"
Rev = ""
for char in Y:
    Rev = char + Rev
if Y == Rev:
    print("Palindrome")
else:
   print("Not Palindrome")

"""Count Vowels in a String"""

Sentence = input("Enter a Sentence: ")
Vowels = "aeiouAEIOU"
Count = 0
for char in Sentence:
  if char in Vowels:
    Count += 1
print(Count)